config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts
  #get 'static/index'
#    root 'static#index'
    root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/catego.rb
class Catego < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/models/categorium.rb
class Categorium < ApplicationRecord
#    validates :catnomb, presence: true
#    has_and_belongs_to_many :posts
#  belongs_to :post
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  has_and_belongs_to_many :categos
  friendly_id :title, use: :slugged
  mount_uploader :imagen, PictureUploader
  validates :description, presence: true
  validates :title, presence: true
  validates :body, presence: true
  validates :fecha, presence: true
#  has_and_belongs_to_many :Categorias

  def should_generate_new_friendly_id?
    title_changed?
  end

  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
    #  all
    #  where('title LIKE ?', "%#{search}%")
      unscoped
    end
  end

  def cat_nom
    self.catego.nombre
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    #@slides = Post.all
    @slider = Post.order(updated_at: :desc).limit(5)
    @sidebar = Post.where(:slider => true).limit(5)
  #  @posts = Post.paginate(:page => params[:page], :per_page => 5)
    @posts = Post.search(params[:search]).paginate(:per_page => 5, :page => params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @sidebar = Post.where(:slider => true)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'La publicación fue creada exitosamente.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'La publicación fue actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_footer.html.erb

<footer>

    <!--/.footer-->

    <div class="footer">
        <div class="container">
             <h3  class="pull-left">Diseñado y Desarrollado por <a href="www.galtec.org">Galtec. </a> </h3>

            <div class="pull-right">
              <ul class="social">
                  <li> <a href="https://www.facebook.com/AqpHoyRevista/"> <i class="fa fa-facebook"> &nbsp; </i> </a> </li>
                  <li> <a href="#"> <i class="fa fa-twitter"> &nbsp; </i> </a> </li>
                  <li> <a href="#"> <i class="fa fa-google-plus"> &nbsp; </i> </a> </li>
                  <li> <a href="#"> <i class="fa fa-pinterest"> &nbsp; </i> </a> </li>
                  <li> <a href="#"> <i class="fa fa-youtube"> &nbsp; </i> </a> </li>
              </ul>
            </div>
        </div>
    </div>
    <!--/.footer-bottom-->
</footer>

app/views/layouts/_navbar.html.erb

<header>
  <nav class="navbar navbar-expand-lg navbar-light">

    <%= link_to (root_path),class: "navbar-brand" do %>
      <%= image_tag("logo.png" , class: "img-fluid") %>
    <% end %>
    <!-- <%=content_tag(:a, "GALTEC",href:root_path) %> -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Inicio", root_path, id: "news", class: "nav-link" %>
          <!-- <a class="nav-link" href="#">Inicio <span class="sr-only">(current)</span></a> -->
        </li>

        <li class="nav-item">
          <a class="nav-link disabled" href="#">Arequipa</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href=<%=rails_admin_path%>>Admin</a>
        </li>
      </ul>
      <%= form_tag root_path, :method => 'get' , :class=>'form-inline my-2 my-lg-0' do %>
        <p>
          <%= text_field_tag :search, params[:search],class:'form-control mr-sm-2' %>
          <%= submit_tag "Buscar", :name => nil ,class:'btn btn-outline-dark my-2 my-sm-0'%>
        </p>
      <% end %>
      <!-- <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Buscar</button>
      </form> -->
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- <title><%= yield(:page_title)%>  | Blogaqp</title> -->
    <%= csrf_meta_tags %>

    <meta name="copyright" content="GalTec, srl. Copyright (c) 2017"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= display_meta_tags site: 'AQP HOY' %>

    <%= favicon_link_tag("logo_32.png") %>
    <%= favicon_link_tag 'logo_32.png', rel: 'apple-touch-icon', type: 'image/png' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans|Open+Sans" rel="stylesheet">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-45964486-3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-45964486-3');
    </script>


  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>

  </body>
  <%= render 'layouts/footer' %>

</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :post_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% title 'Todos los Eventos Arequipa Conciertos, fiestas, eventos y Cultura de AQP' %>
<% description 'Agenda de los mejores eventos, conciertos, eventos, museos, fiestas y diversión de Arequipa al dia a dia.' %>
<% keywords 'Arequipa, Conciertos, Fiestas, Diversion, Salidas, Donde ir, Que Hacer, A donde ' %>

<% provide(:page_title,'Agenda de Eventos Arequipa') %>
<% if @slider.count>=4 %>

<section class="main-banner pt-4 pb-5">
<div class="shell">
		<div class="row mx-auto">
			<div class="col-md-6 p-1">
				<div class="post d-flex">
					<%= cl_image_tag(@slider[0].imagen,:class =>"img-fluid",:alt => @slider[0].title,:width=>860, :height=>662, :crop=>"crop")%>
					<div class="post-caption d-flex flex-column h-100">
	          <ul class="p-3">
	            <li><a href="#"><span class="label label-warning">Eventos</span></a></li>
	          </ul>
	          <div class="text-center mt-auto p-2">
	            <div class="h1">
								<%= link_to(@slider[0]) do %>

									<%= @slider[0].title%>
								<% end %>
							</div>
	            <!-- <div class="post-meta post-meta-hidden-outer">
	              <div class="post-meta-hidden">
	                <div class="icon text-gray icon-lg material-icons-share">
	                  <ul>
	                    <li><a href="#" class="icon fa fa-facebook"></a></li>
	                    <li><a href="#" class="icon fa fa-twitter"></a></li>
	                    <li><a href="#" class="icon fa fa-google-plus"></a></li>
	                    <li><a href="#" class="icon fa fa-linkedin"></a></li>
	                    <li><a href="#" class="icon fa fa-pinterest"></a></li>
	                  </ul>
	                </div>
	              </div><a href="politics.html" class="post-meta-time">
	                <time datetime="2016-06-06" class="htmlme">2h ago</time></a>
	            </div> -->
	          </div>
					</div>
				</div>
			</div>
			<div class="col-sm-12 col-md-6">
				<div class="row">
					<div class="post top-post col-md-6 p-1 d-flex">
						<%= cl_image_tag(@slider[1].imagen,:class =>"img-fluid",:alt => @slider[1].title,:width=>426, :height=>327, :crop=>"crop")%>
						<div class="post-caption d-flex flex-column h-100">
		          <ul class="p-2">
		            <li><a href="#"><span class="label label-warning">Eventos</span></a></li>
		          </ul>
							<div class="text-center mt-auto p-2">
		            <div class="h2">
									<%= link_to(@slider[1]) do %>
										<%= @slider[1].title%>
									<% end %>
								</div>
		            <!-- <div class="post-meta post-meta-hidden-outer">
		              <div class="post-meta-hidden">
		                <div class="icon text-gray icon-lg material-icons-share">
		                  <ul>
		                    <li><a href="#" class="icon fa fa-facebook"></a></li>
		                    <li><a href="#" class="icon fa fa-twitter"></a></li>
		                    <li><a href="#" class="icon fa fa-google-plus"></a></li>
		                    <li><a href="#" class="icon fa fa-linkedin"></a></li>
		                    <li><a href="#" class="icon fa fa-pinterest"></a></li>
		                  </ul>
		                </div>
		              </div><a href="politics.html" class="post-meta-time">
		                <time datetime="2016-06-06" class="htmlme">2h ago</time></a>
		            </div> -->
		          </div>

						</div>
					</div>
					<div class="post top-post col-md-6 p-1 d-flex">
						<%= cl_image_tag(@slider[2].imagen,:class =>"img-fluid",:alt => @slider[2].title,:width=>426, :height=>327, :crop=>"crop")%>
						<div class="post-caption d-flex flex-column h-100">
		          <ul class="p-2">
		            <li><a href="#"><span class="label label-warning">Eventoss</span></a></li>
		          </ul>
							<div class="text-center mt-auto p-2">
		            <div class="h2">
									<%= link_to(@slider[2]) do %>
										<%= @slider[2].title%>
									<% end %>
								</div>
		          </div>
						</div>
					</div>
					<div class="post top-post col-md-6 p-1 d-flex">
						<%= cl_image_tag(@slider[3].imagen,:class =>"img-fluid",:alt => @slider[3].title,:width=>426, :height=>327, :crop=>"crop")%>
						<div class="post-caption d-flex flex-column h-100">
		          <ul class="p-2">
		            <li><a href="#"><span class="label label-warning">Eventos</span></a></li>
		          </ul>
							<div class="text-center mt-auto p-2">
		            <div class="h2">
									<%= link_to(@slider[3]) do %>
										<%= @slider[3].title%>
									<% end %>
								</div>
		          </div>
						</div>
					</div>
					<div class="post top-post col-md-6 p-1 d-flex">
						<%= cl_image_tag(@slider[4].imagen,:class =>"img-fluid",:alt => @slider[4].title,:width=>426, :height=>327, :crop=>"crop")%>
						<div class="post-caption d-flex flex-column h-100">
		          <ul class="p-2">
		            <li><a href="#"><span class="label label-warning">Eventos</span></a></li>
		          </ul>
							<div class="text-center mt-auto p-2">
		            <div class="h2">
									<%= link_to(@slider[4]) do %>
										<%= @slider[4].title%>
									<% end %>
								</div>
		          </div>
						</div>
					</div>
				</div>

			</div>
			</div>

		</div>
</div>

</section>

<% end %>

<!-- </div> -->





<div class="container">
  <H3>Qué hacer en Arequipa</H3>

  <div class="row align-middle">
    <a href="" class="col-sm-6 col-lg-3 image-r text-center ">

      <%= image_tag("cat_post/aqp1.png" , class: "img-fluid", size: "275x200") %>
      <div class="captionn">
        HOY
      </div>
    </a>
    <a href="" class="col-sm-6 col-lg-3 image-r text-center ">
      <!-- <img src="http://res.cloudinary.com/dehhkgwah/image/upload/c_thumb,h_200,w_275/v1511390410/aqp3_m96c2e.jpg" alt="Arequipa Eventos hoy",class= "img-fluid"> -->
      <%= image_tag("cat_post/aqp2.png" , class: "img-fluid", size: "275x200") %>
      <div class="captionn">
        ESTE FIN
      </div>
    </a>
    <a href="" class="col-sm-6 col-lg-3 image-r text-center ">
      <%= image_tag("cat_post/aqp3.png" , class: "img-fluid", size: "275x200") %>
      <div class="captionn">
        ESTA SEMANA
      </div>
    </a>
    <a href="" class="col-sm-6 col-lg-3 image-r text-center ">
      <%= image_tag("cat_post/aqp4.png" , class: "img-fluid", size: "275x200") %>
      <div class="captionn">
        ESTE MES
      </div>
    </a>

  </div>


  <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

          <h1 class="my-4">Eventos recientes
            <small>en Arequipa</small>
          </h1>

          <!-- Blog Post -->

          <% @posts.each do |post| %>
          <div class="card mb-4">
            <%= cl_image_tag(post.imagen,:class =>"card-img-top", :alt => "Sample Image",:width=>900, :height=>300, :crop=>"scale")%>
            <!-- <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap"> -->
            <div class="card-body">
              <h2 class="card-title"><%= post.title %></h2>
              <p class="card-text">
                <% if !post.body.blank? %>
                <%=  truncate(post.body.html_safe, :length => 200, :omission => "" , :escape => false) %>
                <% end %>
              </p>
              <%= link_to 'Leer Mas ->', post ,class: "btn btn-outline-primary"%>

              <!-- <a href=post class="btn btn-primary">Leer Mas &rarr;</a>
              <%= link_to 'Show', post %> -->
            </div>
			      <div class="d-flex flex-row card-footer aqp-postfooter justify-content-center">
			        <% if !post.fecha.blank? %>
			        <div class="p-0"><i class="fa fa-calendar-check-o fa-2x" aria-hidden="true"></i><%= post.fecha.day%>/<%= post.fecha.month%>/<%= post.fecha.year%> </div>
			        <% end %>
			      </div>


          </div>


          <% end %>

          <%= will_paginate @posts, :page_links => false ,:previous_label => '« Anterior ', :next_label => ' Siguiente »',:class=>'pagination justify-content-center mb-4' %>


        </div>

        <div class="top col-md-12 col-lg-4">

            <div class="destacadosTop-title two my-4">
                <p class="">TOP</p>
            </div>
            <div class="top_list">

						<ul>
							<% @sidebar.each do |sidebar| %>
								<%= link_to(sidebar) do%>
									<div class="d-flex flex-column aqpleftside">
										<div class="py-2" style="">
											<div class="imagediv">
												<%=cl_image_tag(sidebar.imagen, :height=>60, :width=>60, :crop=>"scale") %>
											</div>
											<div class="">
												<p ><%= sidebar.title %></p>
												<p class="title_list"><%= sidebar.description %></p>
											</div>
											<div class="gradient_hr">
												<hr size="5">
											</div>
										</div>
									</div>
								<% end %>
							<% end %>
						</ul>
                        <!-- <div class="top-list-button mono">
                            ver más
                        </div> -->
                    <div>
            	</div>
            	</div>
                </div>



  </div>
</div>







<!-- <div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Posts</h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th>Description</th>
        <th>Slug</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.body %></td>
          <td><%= post.description %></td>
          <td><%= post.slug %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Post', new_post_path %>
</div> -->

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% provide(:page_title,@post.title) %>
<% title @post.title %>
<% description 'Agenda de los mejores eventos, conciertos, eventos, museos, fiestas y diversión de Arequipa al dia a dia.'+@post.description %>
<% keywords 'Arequipa, Conciertos, Fiestas, Diversion, Salidas, Donde ir, Que Hacer, A donde ' %>


<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4"><%= @post.title %></h1>

          <!-- Author -->
          <p class="lead">
            Por:
            <a href="#">Blog AQP</a>
          </p>

          <hr>

          <!-- Date/Time -->
          <% if !@post.fecha.blank? %>
            <p>a realizarse el <%= @post.fecha.strftime("%B") %></p>
          <% end %>

          <p>Posted on January 1, 2017 at 12:00 PM</p>

          <hr>

          <!-- Preview Image -->
          <%= cl_image_tag(@post.imagen,:class =>"img-fluid rounded", :alt => @post.title,:width=>900, :height=>300, :crop=>"scale")%>

          <hr>

          <!-- Post Content -->
          <%= @post.body.html_safe %>



        </div>
        <div class="top col-md-12 col-lg-4">
          <div class="destacadosTop-title two my-4">
            <p class="">TOP</p>
          </div>
          <div class="top_list">

            <ul>
              <% @sidebar.each do |sidebar| %>
              <%= link_to(sidebar) do%>
              <div class="d-flex flex-column aqpleftside">
                <div class="py-2" style="">
                  <div class="imagediv">
                    <%=cl_image_tag(sidebar.imagen, :height=>60, :width=>60, :crop=>"scale") %>
                  </div>
                  <div class="">
                    <p ><%= sidebar.title %></p>
                    <p class="title_list"><%= sidebar.description %></p>
                  </div>
                  <div class="gradient_hr">
                    <hr size="5">
                  </div>
                </div>
              </div>
              <% end %>
              <% end %>
            </ul>
          </div>
        </div>
  </div>
</div>

<!-- <%= @post.title %>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @post.slug %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %> -->